version: "3.7"

services:
  app:
    container_name: new_main_app
    build:  ./
    command: bash -c 'uvicorn app.main:app --host 0.0.0.0 --port 8000'
    volumes:
      - ./app:/src/app
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - postgres
networks:
  postgres:
    external: true
    name: postgres